version: '3.8'

services:
  travel-app:
    image: crpi-aer4k3m8uw2sue3f.cn-hangzhou.personal.cr.aliyuncs.com/dzkdzk/travel:latest
    container_name: travel-spring-app
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx1g -XX:+UseG1GC
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      # 挂载文件上传目录
      - /opt/travel/files:/opt/travel/files
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - travel-network


networks:
  travel-network:
    driver: bridge 