# 开发环境配置覆盖文件
# 这个文件用于开发环境的特殊配置，不会被提交到版本控制

version: '3.8'

services:
  # 开发环境下的MySQL配置
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: travel_db_dev
      MYSQL_USER: travel_user_dev
      MYSQL_PASSWORD: travel123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d

  # 开发环境下的Redis配置
  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  # 开发环境下的应用配置
  travel-app:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/travel_db_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=travel_user_dev
      - SPRING_DATASOURCE_PASSWORD=travel123456
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=
      - JAVA_OPTS=-Xmx1g -Xms512m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"  # 远程调试端口
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./src:/app/src  # 源码挂载，支持热重载

  # 开发环境下的Nginx配置
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local 